import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../screens/home_screen.dart';

part 'app_router.g.dart';

/// Router assembled from the strongly typed routes generated by
/// `go_router_builder`.
final GoRouter appRouter = GoRouter(
  debugLogDiagnostics: false,
  initialLocation: const HomeRoute().location,
  routes: $appRoutes,
);

@TypedGoRoute<HomeRoute>(path: '/', name: 'home')
class HomeRoute extends GoRouteData with $HomeRoute {
  const HomeRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return const HomeScreen();
  }
}
